#!/bin/bash



#Generated by command builder r0.3h



bitrate=2048K #95K
file=source.mp4
output=https://localhost:8080/live/bbb/source.mpd
resolution=1280x720 #256x144
script=$(basename "$0")







ffmpeg \
\
-re -fflags +genpts -stream_loop -1 -i $file \
\
-flags +global_header -r 30000/1001 \
\
-filter_complex "settb=AVTB,\
setpts='trunc(PTS/1K)*1K+st(1,trunc(RTCTIME/1K))-1K*trunc(ld(1)/1K)',\
drawbox=x=0:y=0:width=500:height=100:color=black@0.5:t=fill,\
drawtext=text='%{localtime\:%T}.%{eif\:1M*t-1K*trunc(t*1K)\:d\:3}':x=15:y=20:\
fontfile=/usr/share/fonts/truetype/freefont/FreeSans.ttf:fontsize=80:fontcolor=white,\
scale=$resolution" \
\
-pix_fmt yuv420p \
-c:v libx264 \
\
-b:v:0 $bitrate -minrate:v:0 $bitrate -maxrate:v:0 $bitrate -bufsize:v:0 $bitrate/10 \
\
-g:v 30 -keyint_min:v 30 -sc_threshold:v 0 \
\
-color_primaries bt709 -color_trc bt709 -colorspace bt709 \
\
-c:a aac -ar 48000 -b:a 128k \
\
-map 0:v:0 \
-map 0:a:0 \
\
-preset veryfast \
-tune zerolatency \
-x264-params 'sliced-threads=0:nal-hrd=cbr' \
\
-adaptation_sets 'id=0,seg_duration=2.002,streams=v id=1,seg_duration=2.002,streams=a' \
-use_timeline 1 \
-streaming 1 \
-window_size 3 \
-frag_type every_frame \
-ldash 1 \
-utc_timing_url 'https://time.akamai.com/?iso' \
-format_options 'movflags=cmaf' \
-timeout 0.5 \
-write_prft 1 \
-target_latency '3.0' \
-http_user_agent Akamai_Broadcaster_v1.0 \
-http_persistent 1 \
	-init_seg_name \$RepresentationID\$/source_init.\$ext\$ \
	-media_seg_name \$RepresentationID\$/source_chunk_\$Number%05d\$.\$ext\$ \
-f dash \
"$output"